trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: RunDockerImages
    displayName: "Ejecutar imágenes de Docker"
    steps:
      - checkout: self

      - script: |
          echo "Leyendo la lista de imágenes desde images-list.txt"
          images=$(cat images/images-list.txt | grep -v '^#' | awk '{print $1}')
          for image in $images; do
              echo "Validando la imagen: $image"
              if [[ "$image" == *":"* ]]; then
                  echo "Analizando la imagen con tryvi: $image"
                  # Escanea la imagen con Trivy
                  docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --exit-code 1 $image
                  if [ $? -eq 0 ]; then
                      echo "Ejecutando la imagen: $image"
                      docker run $image
                  else
                      echo "Análisis fallido para la imagen: $image"
                  fi
              else
                  echo "Nombre de imagen no válido: $image"
              fi
          done
        displayName: "Ejecutar imágenes de Docker"
