# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self

  - script: |
      echo "Leyendo la lista de im치genes desde images-list.txt"
      images=$(cat images/images-list.txt | grep -v '^#' | awk '{print $1}')
      for image in $images; do
          echo "Validando la imagen: $image"
          if [[ "$image" == *":"* ]]; then
              echo "Analizando la imagen con tryvi: $image"
              # Escanea la imagen con Trivy
                docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --exit-code 1 $image
              if [ $? -eq 0 ]; then
                  echo "Ejecutando la imagen: $image"
                  docker run $image
              else
                  echo "An치lisis fallido para la imagen: $image"
              fi
          else
              echo "Nombre de imagen no v치lido: $image"
          fi
      done
    displayName: "Ejecutar im치genes de Docker"